# Generated by Django 5.1.3 on 2024-12-02 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_coursemodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(default=648672465208720954, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='courses.course'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_link', models.URLField()),
                ('preview_image', models.URLField()),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='courses.class')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='courses.course')),
            ],
        ),
    ]
