# Generated by Django 5.1.3 on 2024-12-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_class_course_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='recordings_images/'),
        ),
    ]
