# Generated by Django 5.1.3 on 2024-12-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_assessmentdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='file',
        ),
    ]
