# Generated by Django 5.1.3 on 2024-12-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_assessment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentdetail',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
